[directives]
    [directives.force_single_line]
        description = "Force statements to be on a single line rather than spread across multiple"
        regex_match = "[ ]+\\n?([+,])\\n?[ ]+"
        regex_replace = " \\1"
    [directives.strip_comments]
        description = "Remove any comments from the code"
        regex_match = "(.*)#.*"
        regex_replace = "\\1"
    [directives.strip_empty_lines]
        description = "Removes any empty lines"
        regex_match = "\\n\\s*\\n"
        regex_replace = '\n'
    [directives.redecorate]
        description = "Expand decorators around functions"

[selectors]
    [selectors.function]
        description = "Selects functions"
    [selectors.class]
        description = "Selects classes"
