[snippets]
    [snippets.tab]
        regex = "\\t"
    [snippets.name]
        regex = "[a-zA-Z_][-a-zA-Z0-9_]+"
    [snippets.string]
        regex = "\\\"[^\\\"\\n]\\\"|\\\"\\\"\\\"[\\.\\n]*\\\"\\\"\\\"|'[^'\\n]'|'''[.\\n]*'''"
    [snippets.number]
        regex = "0x[0-9ABCDEF]+|-?[0-9]+\\.[0-9]+|-?\\.[0-9]+|-?[0-9]+"
    [snippets.boolean]
        regex = "True|False"
    [snippets.comment]
        regex = "#.*"
    [snippets.empty_line]
        regex = "\\n\\s*\\n"
    [snippets.statement]
        regex = "(\\1\\s{4}.*\\n)"

[format_strings]
    [format_strings.exploded_parameters]
        regex = ",\\s*\\n"
    [format_strings.dangling_opening_bracket]
        regex = "((\\(|\\[|{)\\s*\\n\\s*)"
    [format_strings.decorator]
        regex = "@({{name}})"
    [format_strings.commented_line]
        regex = "(.*){{comment}}"
    [format_strings.return_type]
        regex = "\\s*->\\s*({{name}})"
    [format_strings.top_level_function]
        regex = "()(def\\s+({{name}})\\((.+)?\\)({{return_type}})?\\s*:\\n({{statement}}+))"
        dependencies = ["return_type"]
    [format_strings.function]
        regex = "(\\s*){{top_level_function}}"
        dependencies = ["top_level_function"]
    [format_strings.decorated_function]
        regex = "(\\s*)@({{name}})(\\((.+)\\))?\\n\\1({{function}})"
        dependencies = ["function"]
    [format_strings.decorator_call]
        regex = "{{function}}\\1(\\4)\\s*=\\s*({{name}})\\(\\s*((,?{{name}})+)\\s*,\\s*\\)"
        dependencies = ["function"]
    [format_strings.parameter]
        regex = "(({{name}})\\s*(:\\s*({{name}}))?(\\s*=\\s*({{name}}|[\\\"'].*[\\\"']|[0-9]*(\\.[0-9]+)?))?,?\\s*)"
    [format_strings.class]
        regex = "(\\s*)?class\\s+({{name}})(\\((.+)?\\))?:\\n({{statement}}+)"
    [format_strings.attribute]
        regex = "(\\s*)?({{name}})\\s*(:\\s*({{name}})\\s*)?=\\s*{{value}}"
        dependencies = ["value"]
    [format_strings.value]
        regex = "({{name}}|{{string}}|{{number}}|{{boolean}})"
    [format_strings.bare_statement]
        regex = "(\\s*)((({{name}})\\s*=\\s*)?(\\S.*))"
    [format_strings.for_loop]
        regex = "(\\s*)(for .*:)\\n({{statement}}+)"
    [format_strings.import_from]
        regex = "(\\s*)from\\s+(({{name}}\\.?)+)\\s+import\\s+(.+)"
    [format_strings.imported_names]
        regex = "(({{name}}|\\*),?)"
    [format_strings.import]
        regex = "(\\s*)import (({{name}}\\.?)+)"
    [format_strings.undefined]
        regex = "bvfghnbvfghjkiuhjnhbvfddsxc"

[directives]
    [directives.replace_tabs]
        description = "replace all tabs with spaces"
        [[directives.replace_tabs.variations]]
            regex_format_string = "tab"
            regex_replace = "    "
    [directives.force_single_line]
        description = "Force statements to be on a single line rather than spread across multiple"
        [[directives.force_single_line.variations]]
            regex_format_string = "exploded_parameters"
            regex_replace = ", "
        [[directives.force_single_line.variations]]
            regex_format_string = "dangling_opening_bracket"
            regex_replace = " \\2"
    [directives.strip_comments]
        description = "Remove any comments from the code"
        [[directives.strip_comments.variations]]
            regex_format_string = "commented_line"
            regex_replace = "\\1"
    [directives.strip_empty_lines]
        description = "Removes any empty lines"
        [[directives.strip_empty_lines.variations]]
            regex_format_string = "empty_line"
            regex_replace = "\n"
    [directives.redecorate]
        description = "Expand decorators around functions"
        [[directives.redecorate.variations]]
            regex_format_string = "decorated_function"
            regex_replace = "\\1\\5\\1\\9 = \\2(\\9, \\4)\n"
    [directives.redecorate_clean]
        description = "the regex_replace for redecorate can leave messy commas for decorators with no parameters"
        [[directives.redecorate_clean.variations]]
            regex_format_string = "decorator_call"
            regex_replace = "\\1\\3\\1\\4 = \\g<11>(\\g<13>)"

[selectors]
    [selectors.top_level_function]
        model_element = "function"
        description = "Selects top level functions functions"
        top_level_selector = true
        [[selectors.top_level_function.variations]]
            regex_format_string = "top_level_function"
            name = 2
            parameters = 3
            body = 6
            explicit_type = 4
        [selectors.top_level_function.subselectors]
            [selectors.top_level_function.subselectors.function]
                search_text = "body"
            [selectors.top_level_function.subselectors.class]
                search_text = "body"
            [selectors.top_level_function.subselectors.statement]
                search_text = "body"
            [selectors.top_level_function.subselectors.parameter]
                search_text = "parameters"
            [selectors.top_level_function.subselectors.for_loop]
                search_text = "body"
    [selectors.function]
        model_element = "function"
        description = "Selects functions"
        top_level_selector = false
        [[selectors.function.variations]]
            regex_format_string = "function"
            name = 3
            parameters = 4
            body = 7
            explicit_type = 6
        [selectors.function.subselectors]
            [selectors.function.subselectors.function]
                search_text = "body"
            [selectors.function.subselectors.class]
                search_text = "body"
            [selectors.function.subselectors.statement]
                search_text = "body"
            [selectors.function.subselectors.parameter]
                search_text = "parameters"
            [selectors.function.subselectors.for_loop]
                search_text = "body"
    [selectors.parameter]
        model_element = "variable"
        description = "Selects information pertaining to parameters"
        top_level_selector = false
        [[selectors.parameter.variations]]
            regex_format_string = "parameter"
            name = 1
            type = 3
            initial_value = 5
    [selectors.class]
        model_element = "class"
        description = "Selects classes"
        top_level_selector = true
        [[selectors.class.variations]]
            regex_format_string = "class"
            name = 1
            body = 4
            subclasses = 3
        [selectors.class.subselectors]
            [selectors.class.subselectors.attribute]
                search_text = "body"
            [selectors.class.subselectors.class]
                search_text = "body"
            [selectors.class.subselectors.function]
                search_text = "body"
    [selectors.attribute]
        model_element = "variable"
        description = "selects attributes under classes"
        top_level_selector = false
        [[selectors.attribute.variations]]
            regex_format_string = "attribute"
            name = 1
            type = 3
            initial_value = 4
    [selectors.for_loop]
        model_element = "for_loop"
        description = "selects for loops"
        top_level_selector = false
        [[selectors.for_loop.variations]]
            regex_format_string = "for_loop"
            loop = 1
            body = 2
        [selectors.for_loop.subselectors]
            [selectors.for_loop.subselectors.for_loop]
                search_text = "body"
            [selectors.for_loop.subselectors.statement]
                search_text = "body"
    [selectors.statement]
        model_element = "statement"
        description = "selects statements from a string without whitespace prefix"
        top_level_selector = false
        [[selectors.statement.variations]]
            regex_format_string = "bare_statement"
            lhs = 3
            rhs = 4
    [selectors.operation]
        model_element = false
        description = "breaks appart operations "
        top_level_selector = false
    [selectors.dependency]
        model_element = "dependency"
        description = "selects import statements"
        top_level_selector = true
        [[selectors.dependency.variations]]
            regex_format_string = "import_from"
            source = 1
            provides = 3
        [[selectors.dependency.variations]]
            regex_format_string = "import"
            source = 1
            provides = 2
        [selectors.dependency.subselectors]
            [selectors.dependency.subselectors.provided_dependencies]
                search_text = "provides"
    [selectors.provided_dependencies]
        model_element = "basic_string"
        description = "gets the provided entities from an import"
        top_level_selector = false
        [[selectors.provided_dependencies.variations]]
            regex_format_string = "imported_names"
            value = 1


[info]
    name = "python3"
    description = "Support for the python3 language"
    file_extensions = ["py", "pyw"]
    sources = []
    builtins = ["print"]
[json_mappings]
    top_level_function = "functions"
    class = "classes"
    dependency = "dependencies"